name: clean_provider
description: A simple way to apply best practices with flutter and provider.
version: 0.0.1
homepage: https://github.com/elbeicktalat/clean_provider

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0